spring:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        default_batch_fetch_size: 100

jwt:
  header: Authorization
  secret: ${jwt.secret-key}
